spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  hibernate:
    ddl-auto: create-drop
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: debug

